management.path_prefix = /rabbitmq
log.default.level = warning

# MQTT
mqtt.listeners.tcp.default = 1883
mqtt.vhost = /
mqtt.exchange = amq.topic
mqtt.mailbox_soft_limit = 64
mqtt.max_session_expiry_interval_seconds = 0
mqtt.allow_anonymous = false

# # WEB MQTT
web_mqtt.tcp.port = 15675
web_mqtt.ws_path = /mqtt
