input {
	rabbitmq {
		host => "rabbitmq"
		port => 5672
		auto_delete => true
		durable => false
		exchange_type => "topic"
		exchange => "amq.topic"
		key => "event.#"
		user => "${RABBITMQ_USER}"
		password => "${RABBITMQ_PASS}"
		metadata_enabled => "basic"
	}

	# [WARNING] `Event.#` key was deprecated, use `event.#` instead
	rabbitmq {
		host => "rabbitmq"
		port => 5672
		auto_delete => true
		durable => false
		exchange_type => "topic"
		exchange => "amq.topic"
		key => "Event.#"
		user => "${RABBITMQ_USER}"
		password => "${RABBITMQ_PASS}"
		metadata_enabled => "basic"
	}
}

filter {
	uuid {
        target => "[@metadata][uuid]"
    }

	mutate {
		copy => {"[@metadata][rabbitmq_properties][routing-key]" => "[@metadata][index]"}
	}

	mutate {
		lowercase => ["[@metadata][index]"]
	}

	mutate {
		gsub => ["[@metadata][index]", "^event\.", ""]
	}
}

output {
	elasticsearch {
		index => "%{[@metadata][index]}-%{+yyyy.MM}"
		document_id => "%{[@metadata][uuid]}"
		hosts => "elasticsearch:9200"
		user => "logstash_internal"
		password => "${LOGSTASH_INTERNAL_PASSWORD}"
	}

	stdout {
		codec => rubydebug
	}
}
